name: Test, Build and Deploy
on:
  push:
    branches:
    - master

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - name: Test
        env:
          SOME_VAL: 'SOME-RANDOM-NAME'
        run: echo $SOME_VAL
